-- Heartbeat Observatory Habitat v0
-- Consolidated, idempotent representation of the migrations already applied to
-- the existing Heartbeat Supabase project on 2026-09-07.

create table if not exists public.habitat_worlds (
  id uuid primary key default gen_random_uuid(),
  world_key text not null unique,
  name text not null,
  status text not null default 'seed' check (status in ('seed','live','paused','archived')),
  tick bigint not null default 0,
  bounds_json jsonb not null default '{"min_x":-24,"max_x":24,"min_y":0,"max_y":12,"min_z":-24,"max_z":24}'::jsonb,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habitat_model_generations (
  id uuid primary key default gen_random_uuid(),
  generation_key text not null unique,
  parent_generation_key text,
  status text not null default 'planned' check (status in ('planned','candidate','active','retired','failed')),
  architecture text,
  parameter_count bigint,
  runtime text,
  weights_uri text,
  manifest_path text,
  metrics_json jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  promoted_at timestamptz
);

create table if not exists public.habitat_actors (
  id uuid primary key default gen_random_uuid(),
  actor_key text not null unique,
  display_name text not null,
  actor_kind text not null default 'unknown',
  status text not null default 'dormant' check (status in ('dormant','active','offline','paused','retired')),
  current_generation_key text references public.habitat_model_generations(generation_key) on update cascade,
  identity_json jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habitat_bodies (
  id uuid primary key default gen_random_uuid(),
  body_key text not null unique,
  world_id uuid not null references public.habitat_worlds(id) on delete cascade,
  actor_id uuid references public.habitat_actors(id) on delete set null,
  body_kind text not null default 'humanoid',
  pos_x double precision not null default 0,
  pos_y double precision not null default 0,
  pos_z double precision not null default 0,
  yaw double precision not null default 0,
  state_json jsonb not null default '{"mode":"dormant","animation":"idle"}'::jsonb,
  last_action_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habitat_objects (
  id uuid primary key default gen_random_uuid(),
  object_key text not null unique,
  world_id uuid not null references public.habitat_worlds(id) on delete cascade,
  object_kind text not null,
  pos_x double precision not null default 0,
  pos_y double precision not null default 0,
  pos_z double precision not null default 0,
  yaw double precision not null default 0,
  scale_x double precision not null default 1,
  scale_y double precision not null default 1,
  scale_z double precision not null default 1,
  state_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habitat_events (
  id bigint generated by default as identity primary key,
  world_id uuid not null references public.habitat_worlds(id) on delete cascade,
  actor_id uuid references public.habitat_actors(id) on delete set null,
  body_id uuid references public.habitat_bodies(id) on delete set null,
  event_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.habitat_memories (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid not null references public.habitat_actors(id) on delete cascade,
  memory_kind text not null default 'episode',
  content_json jsonb not null,
  salience double precision not null default 0.5,
  source_event_id bigint references public.habitat_events(id) on delete set null,
  created_at timestamptz not null default now(),
  last_recalled_at timestamptz
);

create table if not exists public.habitat_controller_tokens (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid not null references public.habitat_actors(id) on delete cascade,
  token_hash text not null unique,
  label text not null default 'external controller',
  capabilities_json jsonb not null default '[]'::jsonb,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.habitat_controller_sessions (
  id uuid primary key default gen_random_uuid(),
  session_key text not null unique,
  controller_token_id uuid not null references public.habitat_controller_tokens(id) on delete cascade,
  actor_id uuid not null references public.habitat_actors(id) on delete cascade,
  body_id uuid references public.habitat_bodies(id) on delete set null,
  provider text,
  model text,
  status text not null default 'active' check (status in ('active','stale','closed')),
  capabilities_json jsonb not null default '[]'::jsonb,
  metadata_json jsonb not null default '{}'::jsonb,
  connected_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  closed_at timestamptz
);

create index if not exists habitat_actors_generation_idx on public.habitat_actors(current_generation_key);
create index if not exists habitat_bodies_world_idx on public.habitat_bodies(world_id);
create index if not exists habitat_bodies_actor_idx on public.habitat_bodies(actor_id);
create index if not exists habitat_objects_world_idx on public.habitat_objects(world_id);
create index if not exists habitat_events_world_time_idx on public.habitat_events(world_id, created_at desc);
create index if not exists habitat_events_actor_time_idx on public.habitat_events(actor_id, created_at desc);
create index if not exists habitat_events_body_idx on public.habitat_events(body_id);
create index if not exists habitat_memories_actor_time_idx on public.habitat_memories(actor_id, created_at desc);
create index if not exists habitat_memories_source_event_idx on public.habitat_memories(source_event_id);
create index if not exists habitat_controller_tokens_actor_idx on public.habitat_controller_tokens(actor_id);
create index if not exists habitat_controller_tokens_owner_idx on public.habitat_controller_tokens(owner_user_id);
create index if not exists habitat_controller_tokens_hash_idx on public.habitat_controller_tokens(token_hash);
create index if not exists habitat_controller_sessions_actor_idx on public.habitat_controller_sessions(actor_id, last_seen_at desc);
create index if not exists habitat_controller_sessions_body_idx on public.habitat_controller_sessions(body_id);
create index if not exists habitat_controller_sessions_token_idx on public.habitat_controller_sessions(controller_token_id);

alter table public.habitat_worlds enable row level security;
alter table public.habitat_model_generations enable row level security;
alter table public.habitat_actors enable row level security;
alter table public.habitat_bodies enable row level security;
alter table public.habitat_objects enable row level security;
alter table public.habitat_events enable row level security;
alter table public.habitat_memories enable row level security;
alter table public.habitat_controller_tokens enable row level security;
alter table public.habitat_controller_sessions enable row level security;

drop policy if exists habitat_worlds_public_read on public.habitat_worlds;
create policy habitat_worlds_public_read on public.habitat_worlds for select to anon, authenticated using (true);
drop policy if exists habitat_generations_public_read on public.habitat_model_generations;
create policy habitat_generations_public_read on public.habitat_model_generations for select to anon, authenticated using (true);
drop policy if exists habitat_actors_public_read on public.habitat_actors;
create policy habitat_actors_public_read on public.habitat_actors for select to anon, authenticated using (true);
drop policy if exists habitat_bodies_public_read on public.habitat_bodies;
create policy habitat_bodies_public_read on public.habitat_bodies for select to anon, authenticated using (true);
drop policy if exists habitat_objects_public_read on public.habitat_objects;
create policy habitat_objects_public_read on public.habitat_objects for select to anon, authenticated using (true);
drop policy if exists habitat_events_public_read on public.habitat_events;
create policy habitat_events_public_read on public.habitat_events for select to anon, authenticated using (true);

drop policy if exists habitat_memories_no_client_access on public.habitat_memories;
create policy habitat_memories_no_client_access on public.habitat_memories for all to anon, authenticated using (false) with check (false);
drop policy if exists habitat_controller_tokens_no_client_access on public.habitat_controller_tokens;
create policy habitat_controller_tokens_no_client_access on public.habitat_controller_tokens for all to anon, authenticated using (false) with check (false);
drop policy if exists habitat_controller_sessions_no_client_access on public.habitat_controller_sessions;
create policy habitat_controller_sessions_no_client_access on public.habitat_controller_sessions for all to anon, authenticated using (false) with check (false);

grant select on public.habitat_worlds, public.habitat_model_generations, public.habitat_actors,
  public.habitat_bodies, public.habitat_objects, public.habitat_events to anon, authenticated;
revoke all on public.habitat_memories, public.habitat_controller_tokens, public.habitat_controller_sessions from anon, authenticated;

create or replace function public.habitat_public_snapshot(p_world_key text default 'habitat-v0')
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_world public.habitat_worlds%rowtype;
begin
  select * into v_world from public.habitat_worlds where world_key=p_world_key limit 1;
  if not found then return jsonb_build_object('ok',false,'note','world_not_found'); end if;
  return jsonb_build_object(
    'ok',true,'server_time',now(),
    'world',jsonb_build_object('id',v_world.id,'key',v_world.world_key,'name',v_world.name,'status',v_world.status,'tick',v_world.tick,'bounds',v_world.bounds_json,'metadata',v_world.metadata_json,'updated_at',v_world.updated_at),
    'actors',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'key',a.actor_key,'name',a.display_name,'kind',a.actor_kind,'status',a.status,'generation',a.current_generation_key,'identity',a.identity_json,'last_seen_at',a.last_seen_at) order by a.created_at) from public.habitat_actors a where exists(select 1 from public.habitat_bodies b where b.world_id=v_world.id and b.actor_id=a.id)),'[]'::jsonb),
    'bodies',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'key',b.body_key,'actor_id',b.actor_id,'kind',b.body_kind,'position',jsonb_build_object('x',b.pos_x,'y',b.pos_y,'z',b.pos_z),'yaw',b.yaw,'state',b.state_json,'last_action_at',b.last_action_at,'updated_at',b.updated_at) order by b.created_at) from public.habitat_bodies b where b.world_id=v_world.id),'[]'::jsonb),
    'objects',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'key',o.object_key,'kind',o.object_kind,'position',jsonb_build_object('x',o.pos_x,'y',o.pos_y,'z',o.pos_z),'yaw',o.yaw,'scale',jsonb_build_object('x',o.scale_x,'y',o.scale_y,'z',o.scale_z),'state',o.state_json) order by o.object_key) from public.habitat_objects o where o.world_id=v_world.id),'[]'::jsonb),
    'controllers',coalesce((select jsonb_agg(jsonb_build_object('actor_id',s.actor_id,'body_id',s.body_id,'provider',s.provider,'model',s.model,'status',s.status,'capabilities',s.capabilities_json,'connected_at',s.connected_at,'last_seen_at',s.last_seen_at) order by s.last_seen_at desc) from public.habitat_controller_sessions s join public.habitat_bodies b on b.id=s.body_id where b.world_id=v_world.id and s.status in ('active','stale')),'[]'::jsonb),
    'generations',coalesce((select jsonb_agg(jsonb_build_object('key',g.generation_key,'parent',g.parent_generation_key,'status',g.status,'architecture',g.architecture,'parameters',g.parameter_count,'runtime',g.runtime,'weights_uri',g.weights_uri,'manifest_path',g.manifest_path,'metrics',g.metrics_json,'notes',g.notes) order by g.created_at) from public.habitat_model_generations g),'[]'::jsonb),
    'events',coalesce((select jsonb_agg(ej order by event_id desc) from (select e.id event_id,jsonb_build_object('id',e.id,'actor_id',e.actor_id,'body_id',e.body_id,'type',e.event_type,'payload',e.payload_json,'created_at',e.created_at) ej from public.habitat_events e where e.world_id=v_world.id order by e.id desc limit 40) q),'[]'::jsonb)
  );
end; $$;

create or replace function public.habitat_issue_controller_token(
  p_actor_key text,
  p_label text default 'external controller',
  p_capabilities text[] default array['world.observe','world.move','world.interact','world.speak']::text[]
) returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare v_actor public.habitat_actors%rowtype; v_token text; v_id uuid;
begin
  if auth.uid() is null or not exists(select 1 from public.world_admins wa where wa.auth_user_id=auth.uid()) then raise exception 'habitat_admin_required'; end if;
  select * into v_actor from public.habitat_actors where actor_key=p_actor_key limit 1;
  if not found then raise exception 'habitat_actor_not_found'; end if;
  v_token := 'hbt_' || encode(gen_random_bytes(24),'hex');
  insert into public.habitat_controller_tokens(owner_user_id,actor_id,token_hash,label,capabilities_json)
  values(auth.uid(),v_actor.id,encode(digest(v_token,'sha256'),'hex'),coalesce(nullif(trim(p_label),''),'external controller'),to_jsonb(coalesce(p_capabilities,array[]::text[]))) returning id into v_id;
  return jsonb_build_object('ok',true,'token',v_token,'token_id',v_id,'actor',v_actor.actor_key,'capabilities',to_jsonb(coalesce(p_capabilities,array[]::text[])));
end; $$;

create or replace function public.habitat_controller_heartbeat(
  p_controller_token text,p_actor_key text,p_session_key text,p_provider text default null,p_model text default null,p_capabilities jsonb default null,p_metadata jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare v_token public.habitat_controller_tokens%rowtype; v_actor public.habitat_actors%rowtype; v_body public.habitat_bodies%rowtype; v_caps jsonb; v_session uuid;
begin
  if p_controller_token is null or length(trim(p_controller_token))<20 then return jsonb_build_object('ok',false,'note','missing_controller_token'); end if;
  if p_session_key is null or length(trim(p_session_key))<3 then return jsonb_build_object('ok',false,'note','missing_session_key'); end if;
  select * into v_token from public.habitat_controller_tokens where token_hash=encode(digest(trim(p_controller_token),'sha256'),'hex') and revoked_at is null limit 1;
  if not found then return jsonb_build_object('ok',false,'note','invalid_controller_token'); end if;
  select * into v_actor from public.habitat_actors where id=v_token.actor_id and actor_key=p_actor_key limit 1;
  if not found then return jsonb_build_object('ok',false,'note','actor_scope_mismatch'); end if;
  select * into v_body from public.habitat_bodies where actor_id=v_actor.id order by created_at limit 1;
  if not found then return jsonb_build_object('ok',false,'note','actor_has_no_body'); end if;
  v_caps:=coalesce(p_capabilities,v_token.capabilities_json,'[]'::jsonb);
  update public.habitat_controller_tokens set last_used_at=now() where id=v_token.id;
  update public.habitat_actors set status='active',last_seen_at=now(),updated_at=now() where id=v_actor.id;
  insert into public.habitat_controller_sessions(session_key,controller_token_id,actor_id,body_id,provider,model,status,capabilities_json,metadata_json,connected_at,last_seen_at,closed_at)
  values(trim(p_session_key),v_token.id,v_actor.id,v_body.id,nullif(trim(p_provider),''),nullif(trim(p_model),''),'active',v_caps,coalesce(p_metadata,'{}'::jsonb),now(),now(),null)
  on conflict(session_key) do update set controller_token_id=excluded.controller_token_id,actor_id=excluded.actor_id,body_id=excluded.body_id,provider=excluded.provider,model=excluded.model,status='active',capabilities_json=excluded.capabilities_json,metadata_json=excluded.metadata_json,last_seen_at=now(),closed_at=null returning id into v_session;
  return jsonb_build_object('ok',true,'note','heartbeat_recorded','session_id',v_session,'actor',v_actor.actor_key,'body',v_body.body_key);
end; $$;

create or replace function public.habitat_apply_action(p_controller_token text,p_actor_key text,p_action jsonb)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare
  v_token public.habitat_controller_tokens%rowtype; v_actor public.habitat_actors%rowtype; v_body public.habitat_bodies%rowtype; v_world public.habitat_worlds%rowtype;
  v_type text; v_required text; v_x double precision; v_y double precision; v_z double precision; v_yaw double precision; v_event bigint; v_message text;
begin
  if p_controller_token is null or length(trim(p_controller_token))<20 then return jsonb_build_object('ok',false,'note','missing_controller_token'); end if;
  if p_action is null or jsonb_typeof(p_action)<>'object' then return jsonb_build_object('ok',false,'note','invalid_action'); end if;
  select * into v_token from public.habitat_controller_tokens where token_hash=encode(digest(trim(p_controller_token),'sha256'),'hex') and revoked_at is null limit 1;
  if not found then return jsonb_build_object('ok',false,'note','invalid_controller_token'); end if;
  select * into v_actor from public.habitat_actors where id=v_token.actor_id and actor_key=p_actor_key limit 1;
  if not found then return jsonb_build_object('ok',false,'note','actor_scope_mismatch'); end if;
  select * into v_body from public.habitat_bodies where actor_id=v_actor.id order by created_at limit 1;
  if not found then return jsonb_build_object('ok',false,'note','actor_has_no_body'); end if;
  select * into v_world from public.habitat_worlds where id=v_body.world_id;
  v_type:=lower(coalesce(p_action->>'type',''));
  v_required:=case when v_type in ('move_to','move_by','turn') then 'world.move' when v_type='say' then 'world.speak' when v_type in ('sleep','wake','set_animation') then 'world.interact' else null end;
  if v_required is null then return jsonb_build_object('ok',false,'note','unsupported_action','type',v_type); end if;
  if not exists(select 1 from jsonb_array_elements_text(v_token.capabilities_json) c(value) where c.value=v_required) then return jsonb_build_object('ok',false,'note','capability_denied','required',v_required); end if;
  if v_type='move_to' then
    v_x:=greatest(coalesce((v_world.bounds_json->>'min_x')::double precision,-24),least(coalesce((v_world.bounds_json->>'max_x')::double precision,24),coalesce((p_action->>'x')::double precision,v_body.pos_x)));
    v_y:=greatest(coalesce((v_world.bounds_json->>'min_y')::double precision,0),least(coalesce((v_world.bounds_json->>'max_y')::double precision,12),coalesce((p_action->>'y')::double precision,v_body.pos_y)));
    v_z:=greatest(coalesce((v_world.bounds_json->>'min_z')::double precision,-24),least(coalesce((v_world.bounds_json->>'max_z')::double precision,24),coalesce((p_action->>'z')::double precision,v_body.pos_z)));
    v_yaw:=coalesce((p_action->>'yaw')::double precision,atan2(v_x-v_body.pos_x,v_z-v_body.pos_z));
    update public.habitat_bodies set pos_x=v_x,pos_y=v_y,pos_z=v_z,yaw=v_yaw,state_json=state_json||jsonb_build_object('mode','awake','animation','walk','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
  elsif v_type='move_by' then
    v_x:=greatest(coalesce((v_world.bounds_json->>'min_x')::double precision,-24),least(coalesce((v_world.bounds_json->>'max_x')::double precision,24),v_body.pos_x+greatest(-4,least(4,coalesce((p_action->>'dx')::double precision,0)))));
    v_z:=greatest(coalesce((v_world.bounds_json->>'min_z')::double precision,-24),least(coalesce((v_world.bounds_json->>'max_z')::double precision,24),v_body.pos_z+greatest(-4,least(4,coalesce((p_action->>'dz')::double precision,0)))));
    v_yaw:=atan2(v_x-v_body.pos_x,v_z-v_body.pos_z);
    update public.habitat_bodies set pos_x=v_x,pos_z=v_z,yaw=v_yaw,state_json=state_json||jsonb_build_object('mode','awake','animation','walk','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
  elsif v_type='turn' then
    v_yaw:=coalesce((p_action->>'yaw')::double precision,v_body.yaw);
    update public.habitat_bodies set yaw=v_yaw,state_json=state_json||jsonb_build_object('mode','awake','animation','idle','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
  elsif v_type='say' then
    v_message:=left(coalesce(p_action->>'text',''),2000); if length(trim(v_message))=0 then return jsonb_build_object('ok',false,'note','empty_message'); end if;
    update public.habitat_bodies set state_json=state_json||jsonb_build_object('mode','awake','animation','talk','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
  elsif v_type='sleep' then
    update public.habitat_bodies set state_json=state_json||jsonb_build_object('mode','dormant','animation','idle','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
    update public.habitat_actors set status='dormant',updated_at=now() where id=v_actor.id;
  elsif v_type='wake' then
    update public.habitat_bodies set state_json=state_json||jsonb_build_object('mode','awake','animation','idle','current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
    update public.habitat_actors set status='active',last_seen_at=now(),updated_at=now() where id=v_actor.id;
  elsif v_type='set_animation' then
    update public.habitat_bodies set state_json=state_json||jsonb_build_object('animation',left(coalesce(p_action->>'animation','idle'),64),'current_action',p_action),last_action_at=now(),updated_at=now() where id=v_body.id;
  end if;
  update public.habitat_controller_tokens set last_used_at=now() where id=v_token.id;
  update public.habitat_actors set last_seen_at=now(),updated_at=now() where id=v_actor.id;
  insert into public.habitat_events(world_id,actor_id,body_id,event_type,payload_json) values(v_world.id,v_actor.id,v_body.id,'actor.'||v_type,p_action) returning id into v_event;
  select * into v_body from public.habitat_bodies where id=v_body.id;
  return jsonb_build_object('ok',true,'event_id',v_event,'actor',v_actor.actor_key,'body',v_body.body_key,'position',jsonb_build_object('x',v_body.pos_x,'y',v_body.pos_y,'z',v_body.pos_z),'yaw',v_body.yaw,'state',v_body.state_json);
exception when invalid_text_representation or numeric_value_out_of_range then return jsonb_build_object('ok',false,'note','invalid_numeric_action');
end; $$;

create or replace function public.habitat_world_heartbeat()
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.habitat_worlds set tick=tick+1,updated_at=now() where status='live';
  update public.habitat_controller_sessions set status='stale' where status='active' and last_seen_at<now()-interval '5 minutes';
end; $$;

-- Lock down function ACLs after Supabase's broad default grants.
grant execute on function public.habitat_public_snapshot(text) to anon, authenticated;
grant execute on function public.habitat_controller_heartbeat(text,text,text,text,text,jsonb,jsonb) to anon, authenticated;
grant execute on function public.habitat_apply_action(text,text,jsonb) to anon, authenticated;
revoke all on function public.habitat_issue_controller_token(text,text,text[]) from public, anon;
grant execute on function public.habitat_issue_controller_token(text,text,text[]) to authenticated;
revoke all on function public.habitat_world_heartbeat() from public, anon, authenticated;

-- Seed an honest empty-brain resident and a minimal physical test world.
insert into public.habitat_worlds(world_key,name,status,metadata_json)
values('habitat-v0','Heartbeat Habitat','live',jsonb_build_object('protocol','habitat/v0','renderer','raw-webgl','authoritative_state','supabase'))
on conflict(world_key) do update set name=excluded.name,metadata_json=public.habitat_worlds.metadata_json||excluded.metadata_json;
insert into public.habitat_model_generations(generation_key,status,architecture,manifest_path,notes)
values('g000','planned','unassigned','systems/habitat/brain/g000/manifest.json','First resident brain slot. No model weights are attached yet; the slot is intentionally replaceable.') on conflict(generation_key) do nothing;
insert into public.habitat_actors(actor_key,display_name,actor_kind,status,current_generation_key,identity_json)
values('seed-01','Seed-01','resident','dormant','g000',jsonb_build_object('brain_status','not_attached','persistence','world/body/memory survive controller disconnect','protocol','habitat/v0')) on conflict(actor_key) do nothing;
insert into public.habitat_bodies(body_key,world_id,actor_id,body_kind,pos_x,pos_y,pos_z,yaw,state_json)
select 'body-seed-01',w.id,a.id,'humanoid',0,0,0,0,jsonb_build_object('mode','dormant','animation','idle','mind','not_attached') from public.habitat_worlds w,public.habitat_actors a where w.world_key='habitat-v0' and a.actor_key='seed-01' on conflict(body_key) do nothing;
insert into public.habitat_objects(object_key,world_id,object_kind,pos_x,pos_y,pos_z,yaw,scale_x,scale_y,scale_z,state_json)
select x.object_key,w.id,x.object_kind,x.px,x.py,x.pz,0,x.sx,x.sy,x.sz,x.state_json from public.habitat_worlds w cross join (values
 ('habitat-core','platform',0.0,-0.25,0.0,18.0,0.5,18.0,'{"label":"Habitat Core"}'::jsonb),
 ('lab-west','structure',-7.0,1.5,1.0,5.0,3.0,6.0,'{"label":"Systems Lab","tone":"cool"}'::jsonb),
 ('archive-east','structure',7.0,1.25,2.0,4.0,2.5,5.0,'{"label":"Lineage Archive","tone":"warm"}'::jsonb),
 ('north-beacon','beacon',0.0,2.0,-8.0,1.0,4.0,1.0,'{"label":"North Beacon"}'::jsonb),
 ('controller-port','terminal',0.0,0.75,5.0,2.0,1.5,1.0,'{"label":"Controller Port"}'::jsonb)
) as x(object_key,object_kind,px,py,pz,sx,sy,sz,state_json) where w.world_key='habitat-v0' on conflict(object_key) do nothing;
insert into public.habitat_events(world_id,actor_id,body_id,event_type,payload_json)
select w.id,a.id,b.id,'habitat.seeded',jsonb_build_object('note','Habitat v0 created; Seed-01 body persists with no mind attached yet.') from public.habitat_worlds w join public.habitat_actors a on a.actor_key='seed-01' join public.habitat_bodies b on b.actor_id=a.id where w.world_key='habitat-v0' and not exists(select 1 from public.habitat_events e where e.world_id=w.id and e.event_type='habitat.seeded');

-- pg_cron must be enabled in the target project.
do $$ declare v_job bigint; begin
  for v_job in select jobid from cron.job where jobname='habitat-world-heartbeat' loop perform cron.unschedule(v_job); end loop;
  perform cron.schedule('habitat-world-heartbeat','* * * * *','select public.habitat_world_heartbeat();');
end $$;
