// Fortis (the Moon, south pole): the military bloc. Walls, gates, searchlights, red lights, numbered everything. BIBLE-v3 4.2.
// Look: gunmetal and black-olive, bone stencil, signal red. The Unreal Fortis art Jaron liked is the mood reference; nothing is reused.
export default {
  id: 'fortis', name: 'Fortis', kind: 'faction', home: 'moon',
  tagline: 'All clear, until it isn\'t. Badges visible.',
  ethos: 'Hard edges, hard light, hard schedule. Everything is numbered, walled and lit from above; you are always inside a sector. They kept the Moon alive when the storms cut it off, and they would like you to remember that at the gate.',
  palette: { primary: 0x3b4046, secondary: 0x2a2f2a, accent: 0xd22b2b, trim: 0xcfc8b4, dark: 0x14171a, light: 0xdfe9ff, extra: [0x6a6d5a, 0x8a8f94] },
  lights: { ambient: 0xcfdcff, work: 0xe8f0ff, signal: 0xff2a2a, alarm: 0xff2a2a },
  materials: [
    { id: 'gunmetal-plate', name: 'Gunmetal plate', color: 0x3b4046, roughness: 0.55, metalness: 0.8, use: 'walls, gates, hulls, armour: bolted in numbered panels' },
    { id: 'black-olive', name: 'Black-olive paint', color: 0x2a2f2a, roughness: 0.7, metalness: 0.3, use: 'vehicles, barracks doors, gun housings' },
    { id: 'bone-stencil', name: 'Bone stencil paint', color: 0xcfc8b4, roughness: 0.8, metalness: 0.0, use: 'every number, arrow and unit mark, hand-stencilled and slightly crooked' },
    { id: 'regolith-concrete', name: 'Regolith concrete', color: 0x6f6e6a, roughness: 0.98, metalness: 0.0, use: 'barriers, bunkers, the wall base: sintered Moon dust, never painted' },
    { id: 'signal-red', name: 'Signal red', color: 0xd22b2b, roughness: 0.4, metalness: 0.1, use: 'lamps, stripes on officers, danger doors, the one colour allowed to shout' },
  ],
  signs: {
    font: 'Military stencil', fontStack: '"Stencil", "Arial Black", Impact, "Helvetica Neue", sans-serif', weight: 800, upper: true, tracking: 0.14,
    plate: { bg: 0x2a2f2a, fg: 0xcfc8b4, edge: 0x14171a, radius: 0.0, rivets: true },
    warning: { bg: 0xd22b2b, fg: 0xf4f0e4, stripe: [0xd22b2b, 0x14171a] },
    banner: { bg: 0x14171a, fg: 0xcfc8b4 },
    emblem: { shape: 'wedge', fg: 0xd22b2b, bg: 0x2a2f2a, meaning: 'an angular wedge cut with a notch: a breach held shut' },
    numbering: { pattern: 'SECTOR # / BLDG ## / DOOR #', example: 'SECTOR 4 / BLDG 17 / DOOR 2' },
    places: ['Shackleton Gate', 'Fleet Command', 'The Armoury', 'Rim Tower 3', 'Mass Driver Control', 'Gunship Apron'],
    slogans: ['BADGES VISIBLE.', 'ALL CLEAR UNTIL IT ISN\'T.', 'THIS GATE IS NUMBER 7. REMEMBER 7.', 'IF YOU CAN READ THIS YOU ARE STANDING IN THE WRONG PLACE.', 'ORDER IS A RENEWABLE RESOURCE.'],
    graffiti: ['TECHNOS HAS WIFI', 'THE MASS DRIVER IS NOBODY\'S DOG', 'SECTOR 9 IS NOT A SECTOR (WE ASKED)'],
  },
  uniforms: {
    worker: { cloth: 0x6a7078, trim: 0xcfc8b4, note: 'charcoal work fatigues with a stencilled unit number on the chest and a reflective strip: engineers, not infantry' },
    civilian: { cloth: 0x7a7e72, trim: 0xcfc8b4, note: 'surplus: olive and grey, an ID lanyard always on show' },
    guard: { cloth: 0x4a4f4a, trim: 0xd22b2b, note: 'black-olive armoured fatigues, a red shoulder tab, a helmet with a dark visor', helmet: { shell: 0x3b4046, trim: 0xd22b2b, visorTint: 0x1c2128, visorOpacity: 0.78 } },
    officer: { cloth: 0x3b4046, trim: 0xd22b2b, note: 'tailored dark tunic with a red command stripe and brass-free insignia; never wears the helmet, always carries it' },
    pilot: { cloth: 0x5a5f58, trim: 0xcfc8b4, note: 'gunship pilot: grey flight suit, stencilled callsign over the heart', helmet: { shell: 0x4a4f4a, trim: 0xcfc8b4, visorTint: 0x6a6248, visorOpacity: 0.7 } },
    trader: { cloth: 0x8a8f94, trim: 0xd22b2b, note: 'quartermaster in a clean grey smock: the one person with a smile and a form for it' },
    leader: { cloth: 0x2a2f2a, trim: 0xd22b2b, note: 'black tunic, a single red band at the throat; stands at parade rest when sitting' },
  },
  hair: [0x1c140f, 0x3b2416, 0x7a736c, 0xb6b0a4, 0x2a2118],
  architecture: {
    massing: 'Walls inside walls: rectilinear blocks, bastion corners, one big gate per wall, a tower at each corner. Everything squat except the rim power towers and the gun towers.',
    roofs: 'flat, armoured, covered in antennas and searchlights; a red beacon on the highest point',
    windows: 'slits and small square ports with shutters; none at ground level on the outer wall',
    lighting: 'cold white-blue searchlights sweeping, red lamps at doors and gates, dark between pools of light',
    ground: 'grey regolith concrete, painted lane lines, sector numbers stencilled on the ground in bone',
    motifs: ['wedge with notch', 'bastion corner', 'sector number', 'searchlight tower', 'blast door', 'red lamp over a door'],
    props: ['sintered-block barriers', 'checkpoint boom gate', 'ammo crate stack with stencil codes', 'searchlight', 'notice board of orders', 'gun rack', 'vehicle with a numbered door'],
    avoid: ['soft curves and plants (Greenhaven)', 'glass and neon (Technos)', 'anything unnumbered'],
  },
  livery: {
    hull: 0x3b4046, hullAlt: 0x2a2f2a, belly: 0x14171a, trim: 0xcfc8b4, accent: 0xd22b2b, engineGlow: 0xff7a4a,
    stripe: { kind: 'hazard', colors: [0xd22b2b, 0x14171a], widthFrac: 0.05, note: 'red-black hazard on the stern and wing edges, bone stencil numbers on the flank and a red command stripe on leaders' },
    shape: 'The wedge: a flat angular armoured hull, slab sides, a notch cut in the prow, guns you can see. Looks heavy and looks ready. Hardpoints numbered. No rounded edges anywhere.',
    registryPrefix: 'FT-', nameStyle: 'a number and a verb in stencil: FT-07 WARDEN, FT-12 HOLDFAST',
    weathering: { grime: 0.35, scorch: 0.3, patchwork: 0 }, navBeacon: 0xff2a2a,
  },
};
