// GENERATED by tools/gen-registry.mjs - do not hand-edit. Every src/factions/<name>/style.js (F0 faction style sheet; pure data).
// One line per folder; merged with git's union driver (.gitattributes). Run: node tools/gen-registry.mjs

import f_alien from './alien/style.js';
import f_corsairs from './corsairs/style.js';
import f_fortis from './fortis/style.js';
import f_greenhaven from './greenhaven/style.js';
import f_homeguard from './homeguard/style.js';
import f_ironclad from './ironclad/style.js';
import f_mars from './mars/style.js';
import f_mystara from './mystara/style.js';
import f_skyward from './skyward/style.js';
import f_technos from './technos/style.js';
import f_unbound from './unbound/style.js';
import f_wanderhome from './wanderhome/style.js';

export const FACTION_STYLES = [
  f_alien,
  f_corsairs,
  f_fortis,
  f_greenhaven,
  f_homeguard,
  f_ironclad,
  f_mars,
  f_mystara,
  f_skyward,
  f_technos,
  f_unbound,
  f_wanderhome,
];
