// Mystara (Callisto, Valhalla basin): the research institute that went quiet in the storms. Standing instruments, sealed doors,
// violet and gold glyph light. Game fiction, kept vague on purpose. BIBLE-v3 4.4.
export default {
  id: 'mystara', name: 'Mystara', kind: 'faction', home: 'callisto',
  tagline: 'The instrument is listening. Please do not touch it.',
  ethos: 'Dark, deliberate, ceremonial. A scientific institute that has started to behave like a monastery: sealed doors, standing instruments, glyphs that glow when something is measured. They are polite, tired and know more than they say.',
  palette: { primary: 0x2a2540, secondary: 0xd8c27a, accent: 0x9b6bff, trim: 0xf0e6c8, dark: 0x120f1e, light: 0xe9e2ff, extra: [0xffd36b, 0x5a4b8a] },
  lights: { ambient: 0xcdbfff, work: 0xe9e2ff, signal: 0x9b6bff, alarm: 0xffd36b },
  materials: [
    { id: 'violet-basalt', name: 'Violet basalt', color: 0x2a2540, roughness: 0.55, metalness: 0.3, use: 'walls, standing instruments, sealed doors: ground smooth and polished' },
    { id: 'old-gold', name: 'Old gold inlay', color: 0xd8c27a, roughness: 0.3, metalness: 0.95, use: 'glyph lines in floors and doors, instrument rings, trim on uniforms' },
    { id: 'glyph-light', name: 'Glyph light', color: 0x9b6bff, roughness: 0.2, metalness: 0.0, use: 'always emissive: pulses slowly when an instrument is measuring' },
    { id: 'parchment', name: 'Archive parchment', color: 0xf0e6c8, roughness: 0.9, metalness: 0.0, use: 'printed records, notices, the one warm thing in the room' },
    { id: 'frost-ice', name: 'Callisto ice', color: 0xd7e3f4, roughness: 0.4, metalness: 0.0, use: 'the ground outside, stained dark by dust; shows through the windows' },
  ],
  signs: {
    font: 'Engraved serif with glyph numerals', fontStack: '"Palatino Linotype", Palatino, Georgia, serif', weight: 600, upper: true, tracking: 0.2,
    plate: { bg: 0x120f1e, fg: 0xd8c27a, edge: 0x9b6bff, radius: 0.0, rivets: false },
    warning: { bg: 0x9b6bff, fg: 0x120f1e, stripe: [0x120f1e, 0xd8c27a] },
    banner: { bg: 0x2a2540, fg: 0xf0e6c8 },
    emblem: { shape: 'glyph-ring', fg: 0xd8c27a, bg: 0x2a2540, meaning: 'a ring with three notches and an open eye in the middle: three measurements, one witness' },
    numbering: { pattern: 'ARRAY ## / SEAL #', example: 'ARRAY 09 / SEAL 4' },
    places: ['Valhalla Basin', 'The Standing Array', 'Sealed Site Four', 'The Archive', 'Europa Window', 'Quiet Hall'],
    slogans: ['THE INSTRUMENT IS LISTENING.', 'DO NOT TOUCH THE STANDING INSTRUMENTS.', 'WE WILL TELL YOU WHEN WE KNOW.', 'PLEASE STOP ASKING ABOUT SEALED SITE FOUR.', 'MEASURE TWICE. SEAL ONCE.'],
    graffiti: ['SEAL 4 BREATHES', 'THE ARCHIVE REARRANGES ITSELF', 'WE ARE ALSO WORRIED (THE DIRECTORS)'],
  },
  uniforms: {
    worker: { cloth: 0x5a4b8a, trim: 0xd8c27a, note: 'deep violet work robes cut like a lab coat, a gold thread at the collar; hands always in gloves' },
    civilian: { cloth: 0x7a6e9a, trim: 0xf0e6c8, note: 'layered grey-violet knits against the cold; a pocket for a notebook, always full' },
    guard: { cloth: 0x2a2540, trim: 0xd8c27a, note: 'warden of the seals: dark robes with a gold sash and a ring of keys; helmet is a smooth violet shell', helmet: { shell: 0x2a2540, trim: 0xd8c27a, visorTint: 0x5a4b8a, visorOpacity: 0.7 } },
    officer: { cloth: 0x3a3158, trim: 0xd8c27a, note: 'senior researcher: long violet coat, a gold ring-pin showing their clearance level' },
    pilot: { cloth: 0x4a4068, trim: 0xd8c27a, note: 'expedition pilot: padded violet suit, a gold glyph on the sleeve for each lost expedition survived', helmet: { shell: 0x3a3158, trim: 0xd8c27a, visorTint: 0x6a6248, visorOpacity: 0.65 } },
    trader: { cloth: 0x6a5f88, trim: 0xd8c27a, note: 'the archive\'s purchasing clerk: sceptical, receipts in triplicate' },
    leader: { cloth: 0x2a2540, trim: 0xffd36b, note: 'the Director: black-violet with a bright gold ring, speaks slowly, looks at the instrument before answering' },
  },
  hair: [0x1c140f, 0x3b2416, 0x7a736c, 0xb6b0a4, 0xe8e2d4],
  architecture: {
    massing: 'Low, wide, buried halls with standing stones of instrument rising from them; a ring layout around the central array; thick doors; most of it below the surface. Few windows, deliberately placed to face Jupiter.',
    roofs: 'earth-covered or flat-iced; instrument masts and tall glyph-lit monoliths in rings',
    windows: 'a handful of narrow vertical slits and one big viewing window toward Jupiter',
    lighting: 'dim; violet and gold glyph lines in floors and door frames, a slow pulse when something is being measured',
    ground: 'polished basalt with gold inlay, dark ice outside, a ring path worn by footsteps around the array',
    motifs: ['glyph ring with three notches', 'standing monolith', 'sealed door with inlay', 'gold line in floor', 'open eye', 'instrument ring'],
    props: ['standing instrument on a plinth', 'archive drawer', 'brass key ring', 'sealed door with seven locks', 'violet lantern', 'stack of printed records', 'very old coffee machine'],
    avoid: ['bright primary colours', 'anything cheerful and loud (they are not)', 'plain grey military boxes'],
  },
  livery: {
    hull: 0x2a2540, hullAlt: 0x3a3158, belly: 0x120f1e, trim: 0xd8c27a, accent: 0x9b6bff, engineGlow: 0xc4a6ff,
    stripe: { kind: 'glyph', colors: [0xd8c27a, 0x9b6bff], widthFrac: 0.03, note: 'a gold line along the spine with violet glyphs that glow, and a sensor mast or two; no weapons painted on' },
    shape: 'Dark, smooth and a little ritual: a long hull like a tuning fork or a standing stone laid down, sensor masts, no visible weapon mounts. Looks like it is measuring you.',
    registryPrefix: 'MY-', nameStyle: 'a measurement or a prayer, engraved: LISTENING POST, THE THIRD MEASURE',
    weathering: { grime: 0.12, scorch: 0.0, patchwork: 0 }, navBeacon: 0x9b6bff,
  },
};
