// Skyward (Earth): the ones who launch and leave. Launch sites, orbital know-how, tethers if players build them. BIBLE-v3 4.5.
// Look: launch-complex white, range orange, sky blue; gantries, chevrons pointing up, everything numbered in a countdown.
export default {
  id: 'skyward', name: 'Skyward', kind: 'faction', home: 'earth',
  tagline: 'Up is a direction. It is also a career.',
  ethos: 'Clean, bright, optimistic and a little unhinged. Every surface looks like it is waiting for a countdown. They sell Earth\'s bulk to the sky and buy their way into it; their buildings point up and their jokes are about leaving.',
  palette: { primary: 0xf2f4f6, secondary: 0xe8591e, accent: 0x3aa0ff, trim: 0x1b2733, dark: 0x23303d, light: 0xffffff, extra: [0xf5c518, 0x9fb3c4] },
  lights: { ambient: 0xe8f2ff, work: 0xffffff, signal: 0xff6a2a, alarm: 0xff2a2a },
  materials: [
    { id: 'launch-white', name: 'Launch-complex white', color: 0xf2f4f6, roughness: 0.45, metalness: 0.1, use: 'tank farms, hangar skins, ship hulls: scrubbed daily and always slightly yellow near the engines' },
    { id: 'range-orange', name: 'Range orange', color: 0xe8591e, roughness: 0.5, metalness: 0.15, use: 'gantries, service arms, hatches, flight suits' },
    { id: 'gantry-steel', name: 'Gantry lattice', color: 0x9fb3c4, roughness: 0.4, metalness: 0.8, use: 'launch towers, tether anchor frames, catwalks' },
    { id: 'blast-concrete', name: 'Blast concrete', color: 0x8c8c88, roughness: 0.95, metalness: 0.0, use: 'pads and flame trenches (scorched black near the centre)' },
    { id: 'sky-glass', name: 'Sky-blue glass', color: 0x3aa0ff, roughness: 0.08, metalness: 0.2, use: 'control room windows and the training halls' },
  ],
  signs: {
    font: 'Wide clean sans', fontStack: '"Helvetica Neue", Arial, sans-serif', weight: 700, upper: true, tracking: 0.12,
    plate: { bg: 0xf2f4f6, fg: 0x1b2733, edge: 0xe8591e, radius: 0.1, rivets: false },
    warning: { bg: 0xe8591e, fg: 0xffffff, stripe: [0xf2f4f6, 0xe8591e] },
    banner: { bg: 0x3aa0ff, fg: 0xffffff },
    emblem: { shape: 'rising-chevron', fg: 0xe8591e, bg: 0xf2f4f6, meaning: 'two stacked chevrons inside a ring: up, and then up again' },
    numbering: { pattern: 'PAD # / T-MINUS ##', example: 'PAD 4 / T-MINUS 12' },
    places: ['Pad Four', 'The Gantry Bar', 'Range Control', 'Tether Foot', 'Training Hall B', 'Last Handshake Gate'],
    slogans: ['UP IS A DIRECTION. IT IS ALSO A CAREER.', 'T-MINUS EVERYTHING.', 'WE STOPPED SAYING "IF".', 'GRAVITY IS A PHASE.', 'THE SKY IS THE OPEN DOOR (THE DOOR IS ON FIRE)'],
    graffiti: ['HOMEGUARD: STILL HERE. WE NOTICED.', 'SOMEONE LEFT A CAR ON PAD 2', 'COUNTDOWN FROM 10, ARGUE FROM 9'],
  },
  uniforms: {
    worker: { cloth: 0xc9ced3, trim: 0xe8591e, note: 'white coveralls with orange shoulder panels; ground crew carry a clipboard like a weapon' },
    civilian: { cloth: 0xb8c4d2, trim: 0x3aa0ff, note: 'bright layers, orange or sky-blue; hoodies with mission patches nobody earned' },
    guard: { cloth: 0x5a6672, trim: 0xe8591e, note: 'range-safety vest over grey; a white helmet with an orange band', helmet: { shell: 0xe6e9ec, trim: 0xe8591e, visorTint: 0x7a5a32, visorOpacity: 0.55 } },
    officer: { cloth: 0xdde3ea, trim: 0x23303d, note: 'launch director: white jacket, headset always on, never seen sitting' },
    pilot: { cloth: 0xe8591e, trim: 0xf2f4f6, note: 'full orange flight suit, helmet under one arm', helmet: { shell: 0xf2f4f6, trim: 0xe8591e, visorTint: 0x1c2128, visorOpacity: 0.72 } },
    trader: { cloth: 0xaab6c4, trim: 0xe8591e, note: 'sleek shipping-agent coat, a tablet, a suspicious optimism about fuel prices' },
    leader: { cloth: 0xf2f4f6, trim: 0xe8591e, note: 'white from collar to boots with one orange cuff; the only person not wearing a headset, which is a power move' },
  },
  hair: [0x1c140f, 0x3b2416, 0x6b3a22, 0x7a736c, 0xc8a46a],
  architecture: {
    massing: 'Tall, narrow and vertical: towers, gantries and tanks on wide flat pads; low white hangars with big sliding doors; nothing wider than it is tall except the pads.',
    roofs: 'flat or barely domed hangar roofs with orange windsocks; observation decks on stilts',
    windows: 'long ribbon windows in control rooms; none in tank farms; big glass on the training halls so recruits can watch launches',
    lighting: 'floodlit white, orange hazard beacons, a blue strip along every walkway; countdown clock at every junction',
    ground: 'white-lined concrete pads, scorch marks fanning out from the centre, orange-painted kerbs',
    motifs: ['rising chevron', 'ring and arrow', 'lattice gantry', 'countdown number', 'orange service arm', 'windsock'],
    props: ['fuel tanker', 'windsock', 'gantry crane', 'range clock', 'flight-line cones', 'pre-flight checklist board', 'recruit bunk tower'],
    avoid: ['stone and brick (Homeguard)', 'dark military greys (Fortis)', 'anything that looks settled'],
  },
  livery: {
    hull: 0xf2f4f6, hullAlt: 0xdde3ea, belly: 0x8c9aa8, trim: 0x1b2733, accent: 0xe8591e, engineGlow: 0x9fd0ff,
    stripe: { kind: 'chevrons', colors: [0xe8591e, 0xf2f4f6], widthFrac: 0.1, note: 'orange chevrons pointing forward along the dorsal spine and a black-and-white roll pattern on the nose' },
    shape: 'Streamlined launch-vehicle: long, tapered, a nose like a pencil, grid fins and a tail you could balance a rocket on. Ships look fast sitting still. Clean, bright, a little too confident.',
    registryPrefix: 'SW-', nameStyle: 'a verb or a countdown, sans-serif: ASCENT, LIFT-OFF 9, T MINUS',
    weathering: { grime: 0.05, scorch: 0.45, patchwork: 0 }, navBeacon: 0xff6a2a,
  },
};
