// Corsair's Refuge (station faction, a hollowed asteroid in the Belt; dens near every world): the pirates. Scavenged plates, stolen
// transponders on the wall, graffiti. Pirates are at war with everyone. BIBLE-v3 4.7.
export default {
  id: 'corsairs', name: "Corsair's Refuge", kind: 'faction', home: 'station',
  tagline: 'Not pirates. Aggressive recyclers.',
  ethos: 'Loud, stolen and proud of it. Every surface is something else\'s: plates off dead ships, decals of the other factions, transponders nailed up as trophies, spray paint over all of it. Dark metal and hot orange, with a joke on every wall.',
  palette: { primary: 0x3a3a3c, secondary: 0x57534e, accent: 0xff5a1f, trim: 0xe8e0cc, dark: 0x111112, light: 0xf4ecda, extra: [0xe0409a, 0xd9e021, 0x8a4b2a] },
  lights: { ambient: 0xffc89a, work: 0xffd8b0, signal: 0xff5a1f, alarm: 0xe0409a },
  materials: [
    { id: 'scrap-plate', name: 'Scavenged hull plate', color: 0x57534e, roughness: 0.65, metalness: 0.8, use: 'walls, doors, floors: salvaged plates, some still carrying another faction\'s stencil' },
    { id: 'black-hull', name: 'Black hull paint', color: 0x1a1a1c, roughness: 0.5, metalness: 0.4, use: 'ships and the den\'s main surfaces; sprayed over with anything that was in the can' },
    { id: 'spray-orange', name: 'Spray-can orange', color: 0xff5a1f, roughness: 0.4, metalness: 0.0, use: 'tags, arrows, ship numbers, the name of the boss in 2 m letters' },
    { id: 'stolen-decal', name: 'Stolen decal', color: 0xe8e0cc, roughness: 0.6, metalness: 0.0, use: 'transponder plates and faction stencils cut from other ships, mounted like trophies' },
    { id: 'rust-weld', name: 'Rust and weld', color: 0x8a4b2a, roughness: 0.9, metalness: 0.6, use: 'repairs, patches, brackets: nothing is ever replaced, only added to' },
  ],
  signs: {
    font: 'Spray-can capitals', fontStack: '"Impact", "Arial Black", "Marker Felt", sans-serif', weight: 800, upper: true, tracking: 0.04,
    plate: { bg: 0x111112, fg: 0xff5a1f, edge: 0xe0409a, radius: 0.0, rivets: true },
    warning: { bg: 0xe0409a, fg: 0x111112, stripe: [0xd9e021, 0x111112] },
    banner: { bg: 0x3a3a3c, fg: 0xe8e0cc },
    emblem: { shape: 'jolly-wrench', fg: 0xe8e0cc, bg: 0x111112, meaning: 'a skull built from three plates, with a wrench and a cutter crossed behind it: we take it apart' },
    numbering: { pattern: 'DEN #, WHATEVER FLOOR', example: 'DEN 3, WHATEVER FLOOR' },
    places: ['The Refuge', 'The Wall of Transponders', 'Spare Parts Alley', 'Honest Kate\'s Exchange', 'The Back Dock', 'Dead Man\'s Hold (cheap)'],
    slogans: ['NOT PIRATES. AGGRESSIVE RECYCLERS.', 'YES, THAT IS YOUR TRANSPONDER. IT LOOKS BETTER HERE.', 'HONEST PRICES (TO US).', 'WE ARE AT WAR WITH EVERYONE. IT SAVES ON PAPERWORK.', 'NO WEAPONS. (PLEASE HAND IN YOUR WEAPONS.) (WE ARE KIDDING.)'],
    graffiti: ['FORTIS WAS HERE (WE TOOK IT)', 'KATE OWES ME 40', 'IF YOU CAN READ THIS YOU ARE NOT STEALING FAST ENOUGH'],
  },
  uniforms: {
    worker: { cloth: 0x6a6258, trim: 0xff5a1f, note: 'scrap coveralls with a different faction\'s patch on each arm, goggles, an orange bandana' },
    civilian: { cloth: 0x4a4440, trim: 0xe0409a, note: 'leather and chains and an unreasonable number of pockets; an orange or pink dyed streak somewhere' },
    guard: { cloth: 0x2a2a2c, trim: 0xff5a1f, note: 'den bouncer: a stolen Fortis chest plate painted over, a Greenhaven wooden club, very polite until a rule is mentioned', helmet: { shell: 0x57534e, trim: 0xff5a1f, visorTint: 0x7a5a32, visorOpacity: 0.7 } },
    officer: { cloth: 0x3a3a3c, trim: 0xe0409a, note: 'captain: a coat made of at least three other uniforms, a hat with a transponder pinned to it' },
    pilot: { cloth: 0x3a3430, trim: 0xff5a1f, note: 'raider pilot: scarred flight jacket, a lucky charm that is a bolt', helmet: { shell: 0x1a1a1c, trim: 0xff5a1f, visorTint: 0x1c2128, visorOpacity: 0.78 } },
    trader: { cloth: 0x7a6a58, trim: 0xe0409a, note: 'fence: a nice suit that does not fit; a briefcase that is chained to their wrist and empty' },
    leader: { cloth: 0x1a1a1c, trim: 0xff5a1f, note: 'the Admiral of the Refuge: black coat, a hundred transponders sewn into the lining; claims to be a very good cook' },
  },
  hair: [0x1c140f, 0x3b2416, 0x4a2418, 0xb6b0a4, 0x2a1a30],
  architecture: {
    massing: 'Chambers hollowed from an asteroid and fitted out with salvaged compartments from other ships: corridors that bend wherever the rock did, airlocks from three different ship types back to back.',
    roofs: 'the rock itself, hung with cables, nets and the hulls of captured ships on slings',
    windows: 'few; salvaged ports from dead ships, sometimes with the dead ship\'s frosted-glass logo',
    lighting: 'orange work lamps and pink neon scraps, sparks from a welder somewhere, the red-white of a hazard lamp that is there for style',
    ground: 'deck plates from half a dozen ship classes, mismatched and rattling; spilled something sticky',
    motifs: ['skull from three plates', 'crossed wrench and cutter', 'stolen transponder plate', 'spray tag', 'mismatched airlock door', 'hanging net of parts'],
    props: ['transponder wall', 'shelf of mismatched helmets', 'parts bin labelled "MAYBE"', 'a stolen faction flag used as a blanket', 'welding bench with a mug of tea', 'dartboard of a rival\'s face', 'huge honest-looking scale (it is rigged)'],
    avoid: ['tidy and matched anything', 'clean white', 'official signage that is not defaced'],
  },
  livery: {
    hull: 0x1a1a1c, hullAlt: 0x57534e, belly: 0x111112, trim: 0xe8e0cc, accent: 0xff5a1f, engineGlow: 0xff8a3a,
    stripe: { kind: 'scrap', colors: [0xff5a1f, 0xe0409a, 0xe8e0cc], widthFrac: 0.12, note: 'a black base with mismatched grey plates (some with another faction\'s stencil), orange spray numbers, a pink tag, and a transponder plate welded by the cockpit' },
    shape: 'The stripped racer: a lean fast hull with panels removed for speed and plates added for luck, an oversized engine, a boarding hook and nets. Never symmetric. Looks like what it is: a thief that has outrun a lot of people.',
    registryPrefix: 'CR-', nameStyle: 'a rude word or a gift in spray capitals: PARDON ME, REFUND, YOUR LOSS',
    weathering: { grime: 0.55, scorch: 0.4, patchwork: 0.9 }, navBeacon: 0xe0409a,
  },
};
