// Wanderhome (station faction, the Long Walk in high Mars orbit): the nomad network, couriers and gossips. Teal, canvas, lanterns,
// mismatched everything. Modular ships. BIBLE-v3 4.7.
export default {
  id: 'wanderhome', name: 'Wanderhome', kind: 'faction', home: 'station',
  tagline: 'Third door on the left, if it is still there.',
  ethos: 'Warm, cluttered and cheerful. A fleet that is also a village: modules and hulls lashed together, canvas awnings over docking collars, lanterns on every corner. Nothing matches and everyone knows where everything is. They know what the Moon is paying for water this week.',
  palette: { primary: 0x1f7a7a, secondary: 0xd9c9a0, accent: 0xffb347, trim: 0xb5432f, dark: 0x1b2f33, light: 0xf6efd8, extra: [0x8a5aa0, 0x4a8a3a, 0xd9a43a, 0x3a6aa8] },
  lights: { ambient: 0xffe2b0, work: 0xffd98a, signal: 0xffb347, alarm: 0xff6a3a },
  materials: [
    { id: 'teal-enamel', name: 'Teal enamel', color: 0x1f7a7a, roughness: 0.45, metalness: 0.4, use: 'the base colour of modules; chipped to the primer at every corner' },
    { id: 'canvas', name: 'Weathered canvas', color: 0xd9c9a0, roughness: 0.95, metalness: 0.0, use: 'awnings over docking collars, partition walls, sails on the market deck' },
    { id: 'patch-panel', name: 'Mismatched patch panel', color: 0xb5432f, roughness: 0.6, metalness: 0.5, use: 'repair plates in any colour that was on the shelf: red, purple, green' },
    { id: 'lantern-glass', name: 'Lantern glass', color: 0xffb347, roughness: 0.15, metalness: 0.0, use: 'the lanterns, always emissive and swinging a little in the spin' },
    { id: 'rope-and-cable', name: 'Rope, cable, tape', color: 0x8a7a5a, roughness: 0.95, metalness: 0.0, use: 'lashing everywhere; bundles of cable along every wall, labelled in three hands' },
  ],
  signs: {
    font: 'Painted signboard script', fontStack: '"Trebuchet MS", "Marker Felt", "Segoe Print", cursive, sans-serif', weight: 700, upper: false, tracking: 0.02,
    plate: { bg: 0x1b2f33, fg: 0xffe2b0, edge: 0xffb347, radius: 0.22, rivets: false },
    warning: { bg: 0xb5432f, fg: 0xf6efd8, stripe: [0xb5432f, 0xd9c9a0] },
    banner: { bg: 0x1f7a7a, fg: 0xf6efd8 },
    emblem: { shape: 'lantern', fg: 0xffb347, bg: 0x1f7a7a, meaning: 'a hanging lantern with a small route line under it: someone has left a light on for you' },
    numbering: { pattern: 'Berth ## (probably)', example: 'Berth 12 (probably)' },
    places: ['The Long Walk', 'Lantern Row', 'The Gossip Deck', 'Berth 12 (probably)', 'Canvas Market', 'Third Door On The Left'],
    slogans: ['Third door on the left, if it is still there.', 'Gossip is currency. Today\'s rate: high.', 'We know what the Moon is paying for water.', 'Lost anything? We found it. Maybe.', 'No, you may not take the lantern.'],
    graffiti: ['THE WALK MOVED AGAIN', 'BERTH 7 IS A LIE', 'ASK FOR PIP. PIP KNOWS (PIP IS A GOAT)'],
  },
  uniforms: {
    worker: { cloth: 0x4a8a8a, trim: 0xffb347, note: 'teal coveralls worn open over a patterned shirt, a tool belt, a bandana in a different colour every day' },
    civilian: { cloth: 0xb89a6a, trim: 0xb5432f, note: 'layers upon layers: waistcoats, shawls, a hat that has seen things' },
    guard: { cloth: 0x4a6a6a, trim: 0xffb347, note: 'dock-warden: a canvas coat with a lantern on a pole and a whistle; mostly a friendly bouncer', helmet: { shell: 0x1f7a7a, trim: 0xffb347, visorTint: 0x7a5a32, visorOpacity: 0.5 } },
    officer: { cloth: 0x2f6a6a, trim: 0xffb347, note: 'the Dockmaster: a coat embroidered with every route taken; a monocle that is a lens off a camera' },
    pilot: { cloth: 0x7a7a5a, trim: 0xb5432f, note: 'courier pilot: long coat, scarf, goggles; always eating', helmet: { shell: 0x1f7a7a, trim: 0xffb347, visorTint: 0x6a6248, visorOpacity: 0.65 } },
    trader: { cloth: 0xc9a46a, trim: 0x1f7a7a, note: 'bartering stall-keeper: a cloak of many pockets, bells on the cuff so you know they are talking to you' },
    leader: { cloth: 0x1f7a7a, trim: 0xffb347, note: 'the Walker-in-Chief: no one voted for the coat; everyone is used to it' },
  },
  hair: [0x1c140f, 0x3b2416, 0x8a3a22, 0x7a736c, 0x2a5a6a],
  architecture: {
    massing: 'Modules, containers and old hulls lashed together into streets and squares in a spinning ring; rope bridges, ladders, awnings, a market under a patchwork canopy. Always one more annex bolted on.',
    roofs: 'canvas awnings and tarps, solar blankets, strings of lanterns, a goat on a roof (it is Pip)',
    windows: 'portholes, cut-outs, ship windows of every shape, curtains of every cloth',
    lighting: 'warm lantern amber everywhere, teal wash from the old ship lights, string lights across the squares',
    ground: 'grating, rope mats, rugs on the main squares; handwritten arrows on tape',
    motifs: ['lantern', 'canvas awning', 'patch panel in a wrong colour', 'rope lashing', 'hand-lettered sign', 'string lights'],
    props: ['hanging lantern', 'rope ladder', 'market stall with a bell', 'mismatched chairs around a barrel', 'noticeboard thick with notes', 'coffee urn', 'goat'],
    avoid: ['matching colour schemes', 'clean white (Skyward, Technos)', 'weapons on display'],
  },
  livery: {
    hull: 0x1f7a7a, hullAlt: 0x8a5aa0, belly: 0x1b2f33, trim: 0xd9c9a0, accent: 0xffb347, engineGlow: 0xffd070,
    stripe: { kind: 'patchwork', colors: [0xb5432f, 0xd9a43a, 0x4a8a3a, 0x8a5aa0], widthFrac: 0.2, note: 'a teal base with repair panels in several mismatched colours, an awning over the airlock, lanterns on the rails' },
    shape: 'Modular and lashed: a core hull with bolt-on pods, a cargo cage and a sail-like awning; no two Wanderhome ships have the same silhouette. Looks like a caravan, flies like a courier.',
    registryPrefix: 'WH-', nameStyle: 'a place or a joke, painted by hand: Probably Fine, Second Wind, Aunt Pip',
    weathering: { grime: 0.35, scorch: 0.1, patchwork: 0.8 }, navBeacon: 0xffb347,
  },
};
