// Technos Prime (the Moon, far side, Daedalus): dishes, relay, chip fabs, software. Glass, white panels, blue light. BIBLE-v3 4.2.
export default {
  id: 'technos', name: 'Technos Prime', kind: 'faction', home: 'moon',
  tagline: 'Signal over noise. Your data is safe with us (legally).',
  ethos: 'Cool, quiet, expensive. Everything is white, smooth and faintly lit from within; the dishes listen and the people are very polite about it. The neon only comes out when the city is rich and competing.',
  palette: { primary: 0xeef3f8, secondary: 0x9fb4c8, accent: 0x38a8ff, trim: 0x2b3a4d, dark: 0x0f1722, light: 0xffffff, extra: [0xff3fa4, 0x7ae0ff] },
  lights: { ambient: 0xdcecff, work: 0xf4faff, signal: 0x38a8ff, alarm: 0xff3fa4 },
  materials: [
    { id: 'panel-white', name: 'Ceramic white panel', color: 0xeef3f8, roughness: 0.3, metalness: 0.05, use: 'walls, dish backs, ship skins: seamless panels with fine groove lines' },
    { id: 'smart-glass', name: 'Smart glass', color: 0x9fb4c8, roughness: 0.05, metalness: 0.3, use: 'towers, domes, doors: tints to blue when it is listening' },
    { id: 'blue-led', name: 'Blue light strip', color: 0x38a8ff, roughness: 0.2, metalness: 0.0, use: 'edges of floors, handrails, outlines of doors: always emissive' },
    { id: 'dark-chip', name: 'Dark silicon', color: 0x0f1722, roughness: 0.15, metalness: 0.6, use: 'server halls and fab floors; panels with a faint rainbow sheen' },
    { id: 'neon-pink', name: 'Neon tube', color: 0xff3fa4, roughness: 0.2, metalness: 0.0, use: 'competing-Moon signage only: the spoof shops and the bars' },
  ],
  signs: {
    font: 'Light geometric sans, lower case', fontStack: '"Avenir Next", "Segoe UI", "Helvetica Neue", Arial, sans-serif', weight: 300, upper: false, tracking: 0.04,
    plate: { bg: 0x0f1722, fg: 0xdcecff, edge: 0x38a8ff, radius: 0.18, rivets: false },
    warning: { bg: 0xff3fa4, fg: 0x0f1722, stripe: [0x0f1722, 0x38a8ff] },
    banner: { bg: 0xeef3f8, fg: 0x2b3a4d },
    emblem: { shape: 'dish', fg: 0x38a8ff, bg: 0xeef3f8, meaning: 'a dish with three listening arcs: we hear everything, and so politely' },
    numbering: { pattern: 'node-## / bay-#', example: 'node-24 / bay-3' },
    places: ['Daedalus Station', 'The Quiet Dish', 'Fab Floor 2', 'Embassy Ring', 'Relay Control', 'the Back Room (no sign)'],
    slogans: ['signal over noise.', 'have you tried turning the Moon off and on again?', 'your data is safe with us. legally.', 'listening, respectfully.', 'we do not spoof. we simulate.'],
    graffiti: ['FORTIS CAN HEAR THIS WALL', 'PASSWORD IS PASSWORD1 (WE SHOULD TALK)', 'THE DISH IS WATCHING YOU TYPE THIS'],
  },
  uniforms: {
    worker: { cloth: 0xdfe8f2, trim: 0x38a8ff, note: 'white technician smock with blue piping and a glove-pocket for tools; soft-soled shoes, because quiet' },
    civilian: { cloth: 0xc8d4e2, trim: 0x2b3a4d, note: 'minimal layers in white, grey and one accent colour; smart-glass spectacles' },
    guard: { cloth: 0x7a8aa0, trim: 0x38a8ff, note: 'embassy security: tailored blue-grey, an earpiece, no visible weapon (it is very visible if you look)' },
    officer: { cloth: 0xeef3f8, trim: 0x38a8ff, note: 'long white coat, blue light-line down the sleeve; the chief engineers' },
    pilot: { cloth: 0xb8c8da, trim: 0x38a8ff, note: 'pale flight suit with a heads-up visor band; thin hulls make careful pilots', helmet: { shell: 0xeef3f8, trim: 0x38a8ff, visorTint: 0x2a3340, visorOpacity: 0.6 } },
    trader: { cloth: 0xa8b4c4, trim: 0xff3fa4, note: 'a spoof-shop clerk: very good jacket, very neutral face, one neon pink thread' },
    leader: { cloth: 0xf4faff, trim: 0x38a8ff, note: 'all white, glass-clear badge; speaks quietly so that you lean in' },
  },
  hair: [0x1c140f, 0x3b2416, 0x9a9aa6, 0xe8e2d4, 0x2c3a5a],
  architecture: {
    massing: 'Glass towers and white domes growing out of the crater walls; dishes fanned across the floor; long low fab halls. Smooth, seamless, no visible joins.',
    roofs: 'domes and dishes; flat roofs with antenna gardens; skylights over the server halls',
    windows: 'full-height glass; privacy tint on demand; no curtains anywhere',
    lighting: 'cool white inside, blue edge-lighting at night; the competing Moon adds neon along the embassy ring',
    ground: 'polished pale composite, thin blue guide lines, almost no litter (a fine is automatic)',
    motifs: ['dish with arcs', 'blue light-line', 'seamless panel', 'glass tower', 'sphere pod', 'node number'],
    props: ['server rack', 'dish on a plinth', 'drone charging cradle', 'sleek kiosk', 'glass door with a status colour', 'quiet room pod', 'dusty antique keyboard (a museum piece, they claim)'],
    avoid: ['rough concrete (Fortis)', 'wood and plants (Greenhaven)', 'lanterns and canvas (Wanderhome)'],
  },
  livery: {
    hull: 0xeef3f8, hullAlt: 0xd0dbe8, belly: 0x9fb4c8, trim: 0x2b3a4d, accent: 0x38a8ff, engineGlow: 0x7ae0ff,
    stripe: { kind: 'lightline', colors: [0x38a8ff, 0xeef3f8], widthFrac: 0.012, note: 'a thin blue light-line along the whole flank and around the canopy; a pink one on a spoof-shop ship' },
    shape: 'Thin-skinned and elegant: long smooth hull, a glass bubble canopy, an antenna ring or small dish somewhere. Almost no visible weapons. Looks like a piece of equipment, not a warship.',
    registryPrefix: 'TP-', nameStyle: 'a lower-case protocol or a greek letter: packet, delta-9, handshake',
    weathering: { grime: 0.03, scorch: 0.05, patchwork: 0 }, navBeacon: 0x38a8ff,
  },
};
