// GENERATED by tools/gen-registry.mjs - do not hand-edit. Every src/ships/<name>/def.js (server-safe).
// One line per folder; merged with git's union driver (.gitattributes). Run: node tools/gen-registry.mjs

import s_courier from './courier/def.js';
import s_hauler from './hauler/def.js';
import s_meridian from './meridian/def.js';
import s_raider from './raider/def.js';

export const SHIP_DEFS = [
  s_courier,
  s_hauler,
  s_meridian,
  s_raider,
];
