// GENERATED by tools/gen-registry.mjs - do not hand-edit. Every src/ships/<name>/def.js (server-safe).
// One line per folder; merged with git's union driver (.gitattributes). Run: node tools/gen-registry.mjs

import s_bulker from './bulker/def.js';
import s_courier from './courier/def.js';
import s_descender from './descender/def.js';
import s_escort from './escort/def.js';
import s_hauler from './hauler/def.js';
import s_lifeboat from './lifeboat/def.js';
import s_meridian from './meridian/def.js';
import s_raider from './raider/def.js';
import s_transport from './transport/def.js';

export const SHIP_DEFS = [
  s_bulker,
  s_courier,
  s_descender,
  s_escort,
  s_hauler,
  s_lifeboat,
  s_meridian,
  s_raider,
  s_transport,
];
