// Ironclad (Ceres, Occator): the miners. Pit heads, smelters, gantries, amber work lights, hard hats. They build hulls. BIBLE-v3 4.3.
export default {
  id: 'ironclad', name: 'Ironclad', kind: 'faction', home: 'ceres',
  tagline: 'Union made. Union broken. Union made again.',
  ethos: 'Heavy, scorched and warm. Everything is riveted, hand-painted and lit amber; the walls are salt-stained and the humour is gallows. They build the hulls everyone flies in and would like a thank-you note.',
  palette: { primary: 0x5a4a40, secondary: 0x8c8f93, accent: 0xffa21a, trim: 0xe8c03a, dark: 0x211c19, light: 0xf0e6d2, extra: [0x9a4a2d, 0xd8d4c4] },
  lights: { ambient: 0xffc477, work: 0xffb347, signal: 0xffa21a, alarm: 0xff3a1a },
  materials: [
    { id: 'oxide-plate', name: 'Oxide-red plate', color: 0x9a4a2d, roughness: 0.75, metalness: 0.6, use: 'smelter shells, hull plating, tanks: primer showing through the paint' },
    { id: 'galvanised-steel', name: 'Galvanised steel', color: 0x8c8f93, roughness: 0.45, metalness: 0.85, use: 'gantries, walkways, ladders, pit-head frames' },
    { id: 'soot-brick', name: 'Soot-black brick', color: 0x2e2824, roughness: 0.95, metalness: 0.0, use: 'the older furnaces and the union hall' },
    { id: 'hardhat-yellow', name: 'Hard-hat yellow', color: 0xe8c03a, roughness: 0.45, metalness: 0.0, use: 'helmets, handrails, painted edges, hazard stripes' },
    { id: 'salt-flat', name: 'Occator salt crust', color: 0xd8d4c4, roughness: 0.6, metalness: 0.0, use: 'the white crust that gets on everything near the flats' },
  ],
  signs: {
    font: 'Hand-painted block capitals', fontStack: '"Impact", "Arial Black", "Haettenschweiler", sans-serif', weight: 800, upper: true, tracking: 0.05,
    plate: { bg: 0x211c19, fg: 0xffb347, edge: 0xe8c03a, radius: 0.02, rivets: true },
    warning: { bg: 0xe8c03a, fg: 0x211c19, stripe: [0xe8c03a, 0x211c19] },
    banner: { bg: 0x9a4a2d, fg: 0xf0e6d2 },
    emblem: { shape: 'pit-gear', fg: 0xffa21a, bg: 0x211c19, meaning: 'a gear with a pick through it: the work, and the tool for answering back' },
    numbering: { pattern: 'PIT ## / SHIFT #', example: 'PIT 07 / SHIFT 2' },
    places: ['Occator Works', 'Pit Head 7', 'The Union Hall', 'Smelter Row', 'Ore Sorter', 'The Cage (it is a lift)'],
    slogans: ['DAYS WITHOUT ACCIDENT: 0', 'UNION MADE. UNION BROKEN. UNION MADE AGAIN.', 'NO SALT IN THE FURNACE.', 'IF IT IS NOT BOLTED DOWN IT IS A SHIFT-LEAD\'S', 'WE BUILT THE HULL YOU ARE STANDING ON.'],
    graffiti: ['GREENHAVEN: SEND TOMATOES', 'THE SALT WINS EVENTUALLY', 'PIT 3 IS HAUNTED (BY PIT 2)'],
  },
  uniforms: {
    worker: { cloth: 0x8a534c, trim: 0xe8c03a, note: 'oxide-brown coveralls, hi-vis chest strips, a yellow hard hat with a lamp and the pit number stencilled on it', helmet: { shell: 0xe8c03a, trim: 0x211c19, visorTint: 0x7a5a32, visorOpacity: 0.5 } },
    civilian: { cloth: 0x7d6a58, trim: 0xffa21a, note: 'patched work shirts, thick braces, a union pin on every collar' },
    guard: { cloth: 0x4a423c, trim: 0xe8c03a, note: 'shift-marshal: dark coveralls, yellow sash, a big wrench worn like a sceptre', helmet: { shell: 0x2e2824, trim: 0xe8c03a, visorTint: 0x7a5a32, visorOpacity: 0.65 } },
    officer: { cloth: 0x6a4a3c, trim: 0xffa21a, note: 'foreman: cleaner coveralls, a clipboard and a whistle; the white hat means they do not dig' },
    pilot: { cloth: 0x7a6552, trim: 0xe8c03a, note: 'barge pilot in a quilted jacket and welders\' goggles', helmet: { shell: 0x9a4a2d, trim: 0xe8c03a, visorTint: 0x7a5a32, visorOpacity: 0.7 } },
    trader: { cloth: 0x9a7b62, trim: 0xe8c03a, note: 'ore broker with a loupe on a cord and flour-white salt on the cuffs' },
    leader: { cloth: 0x5a4a40, trim: 0xffa21a, note: 'union boss: the same coveralls as everyone with a bright amber scarf and very clean hands, which is suspicious' },
  },
  hair: [0x1c140f, 0x3b2416, 0x6b3a22, 0x7a736c, 0x4a2418],
  architecture: {
    massing: 'Heavy, ribbed industrial blocks around a pit; chimneys, conveyor bridges, a gantry over everything. Dormitory blocks in rows behind the works; the union hall in black brick with a clock.',
    roofs: 'corrugated sheds, saw-tooth factory roofs, a chimney every thirty metres; amber lamps on every ridge',
    windows: 'small steel-framed grids, wired glass; furnace glow through the doors',
    lighting: 'amber work lamps everywhere, orange furnace light from below, white flood on the pit head',
    ground: 'trodden salt and grit, rails, chain-link, yellow-painted kerbs, puddles of brine',
    motifs: ['gear with pick', 'rivet rows', 'saw-tooth roof', 'chimney', 'hazard chevron', 'stencilled pit number'],
    props: ['ore cart on rails', 'forge hammer', 'hard-hat locker row', 'brine drum', 'accident-days board', 'chain hoist', 'kettle on a furnace'],
    avoid: ['clean white (Skyward/Technos)', 'plants and glass (Greenhaven)', 'unpainted new metal: everything is used'],
  },
  livery: {
    hull: 0x9a4a2d, hullAlt: 0x7a3a22, belly: 0x211c19, trim: 0x8c8f93, accent: 0xe8c03a, engineGlow: 0xffa21a,
    stripe: { kind: 'hazard', colors: [0xe8c03a, 0x211c19], widthFrac: 0.07, note: 'yellow-black hazard on the loading edges and a big white pit number on the flank' },
    shape: 'Slab-sided, riveted, over-plated: a hauler or a barge built by people who weld their own opinions on. Cranes, grapples and a big stern. Ugly in the way a good tool is.',
    registryPrefix: 'IC-', nameStyle: 'a pit or a foreman\'s surname in block letters: PIT SEVEN, OLD HANRAHAN',
    weathering: { grime: 0.6, scorch: 0.35, patchwork: 0.2 }, navBeacon: 0xffa21a,
  },
};
