// Greenhaven (Ceres, Kerwan): the farmers and medics. Long glass domes, wood and grown material, green light, gardens. BIBLE-v3 4.3.
export default {
  id: 'greenhaven', name: 'Greenhaven', kind: 'faction', home: 'ceres',
  tagline: 'Grown, not built. Please do not feed the dome.',
  ethos: 'Soft, warm and alive. Curves, wood, cream and leaf-green, a clinic in every other building; light comes through glass and leaves. They cannot build a hull or defend one, and they have made their peace with being the people everyone else needs.',
  palette: { primary: 0xe9efe4, secondary: 0xb08b5c, accent: 0x5fbf6a, trim: 0x2f5d3a, dark: 0x1f2f26, light: 0xfaf7ec, extra: [0xe3b05a, 0xd9795c] },
  lights: { ambient: 0xe4f6cf, work: 0xf4f9e4, signal: 0x7adf8a, alarm: 0xe8794a },
  materials: [
    { id: 'dome-glass', name: 'Dome glass', color: 0xcfe8d8, roughness: 0.05, metalness: 0.1, use: 'the long farm domes: slightly green, slightly fogged with breath' },
    { id: 'grown-wood', name: 'Grown timber', color: 0xb08b5c, roughness: 0.72, metalness: 0.0, use: 'frames, benches, doors, hulls of living ships; grain visible, curved not cut' },
    { id: 'cream-plaster', name: 'Cream plaster', color: 0xe9efe4, roughness: 0.85, metalness: 0.0, use: 'clinic and housing walls, rounded corners' },
    { id: 'leaf-green', name: 'Leaf green', color: 0x5fbf6a, roughness: 0.6, metalness: 0.0, use: 'planting, signage fields, accents on doors and uniforms' },
    { id: 'terracotta', name: 'Terracotta', color: 0xd9795c, roughness: 0.9, metalness: 0.0, use: 'pots, tiles, paving in the gardens and the market' },
  ],
  signs: {
    font: 'Rounded friendly sans', fontStack: '"Trebuchet MS", "Gill Sans", "Segoe UI", sans-serif', weight: 600, upper: false, tracking: 0.02,
    plate: { bg: 0x2f5d3a, fg: 0xfaf7ec, edge: 0xb08b5c, radius: 0.3, rivets: false },
    warning: { bg: 0xe8794a, fg: 0x1f2f26, stripe: [0xe8794a, 0xfaf7ec] },
    banner: { bg: 0xe9efe4, fg: 0x2f5d3a },
    emblem: { shape: 'sun-leaf', fg: 0x5fbf6a, bg: 0xfaf7ec, meaning: 'a leaf growing out of a sun: light turned into dinner' },
    numbering: { pattern: 'Dome # / Row ##', example: 'Dome 3 / Row 14' },
    places: ['Kerwan Domes', 'The Seed Vault', 'Clinic Row', 'Long Dome Two', 'The Gardens', 'Pressure Park'],
    slogans: ['Grown, not built.', 'Please do not feed the dome.', 'Pressure is a feeling. Ask the doctor.', 'Wash your hands, then your tomatoes.', 'Ironclad: send metal. We will send soup.'],
    graffiti: ['THE TOMATOES ARE ORGANISING', 'IRONCLAD CANNOT EAT RIVETS', 'DR. OKAFOR IS NOT A REAL DOCTOR (SHE IS BETTER)'],
  },
  uniforms: {
    worker: { cloth: 0xa8bf9a, trim: 0x2f5d3a, note: 'green canvas smock over a linen shirt, a straw hat, knees dirty from the beds' },
    civilian: { cloth: 0xc9c2a2, trim: 0x5fbf6a, note: 'natural dyes: cream, sage, rust; handmade knitwear in a dome that is always 22 degrees' },
    guard: { cloth: 0x6f8a6a, trim: 0xe3b05a, note: 'dome warden: forest-green vest, a lantern, a lot of patience; their only weapon is the airlock', helmet: { shell: 0xe9efe4, trim: 0x2f5d3a, visorTint: 0x1c2128, visorOpacity: 0.5 } },
    officer: { cloth: 0xe9efe4, trim: 0x5fbf6a, note: 'doctor: white coat, a green cross-leaf on the pocket, a stethoscope that is also a status symbol' },
    pilot: { cloth: 0x9a9a78, trim: 0x2f5d3a, note: 'farm-ship pilot in a padded coat the colour of lettuce', helmet: { shell: 0xe9efe4, trim: 0x5fbf6a, visorTint: 0x6a6248, visorOpacity: 0.55 } },
    trader: { cloth: 0xc9b894, trim: 0xd9795c, note: 'market-stall apron, a scale, a free sample for you' },
    leader: { cloth: 0x4a7a54, trim: 0xe3b05a, note: 'the Warden-Gardener: dark leaf-green coat, a gold seed pin, the calmest person in any room' },
  },
  hair: [0x1c140f, 0x3b2416, 0x6b3a22, 0x7a736c, 0x9a5a38],
  architecture: {
    massing: 'Long barrel-vaulted glass domes in rows, with rounded cream buildings tucked beneath and between; stairs and terraces; clinics at street level. Nothing sharp: corners are rounded, roofs are green.',
    roofs: 'green roofs, glass vaults, curved timber ribs; solar petals on the sunny faces',
    windows: 'large arched or round; planters on every sill; clinic windows have green cross-leaf glass',
    lighting: 'warm daylight through glass, grow-lights in purple-pink on the farm floors, green lamps at clinic doors',
    ground: 'terracotta paving, packed earth paths, planters and benches, water channels you can hear',
    motifs: ['sun-leaf', 'barrel dome', 'rounded corner', 'timber rib', 'planter on a sill', 'green cross-leaf'],
    props: ['seed drawer cabinet', 'watering can', 'hand-cranked pump', 'bench with a plaque', 'tomato trellis', 'clinic bed with a quilt', 'compost bin with a joke label'],
    avoid: ['straight hard-edged slabs (Fortis, Ironclad)', 'white glass-and-neon (Technos)', 'rust and soot'],
  },
  livery: {
    hull: 0xe9efe4, hullAlt: 0xcfe0c8, belly: 0xb08b5c, trim: 0x2f5d3a, accent: 0x5fbf6a, engineGlow: 0xcfffa8,
    stripe: { kind: 'vine', colors: [0x5fbf6a, 0x2f5d3a], widthFrac: 0.05, note: 'a painted vine or leaf line running aft along the flank; a plain green cross-leaf on medical ships' },
    shape: 'Rounded and organic: a seed-pod or a gourd, wooden ribs showing under cream plating, big windows, a garden dome or hold on top. Looks grown. Slow, safe, and unarmed.',
    registryPrefix: 'GH-', nameStyle: 'a plant or a kindness in lower case: Fennel, Second Chance, Good Soup',
    weathering: { grime: 0.1, scorch: 0.0, patchwork: 0 }, navBeacon: 0x7adf8a,
  },
};
