// ============================================================================
// bodies_expanded.js — ADDITIONAL celestial bodies for the SYL solar system.
//
// OWNS: new planet/moon/asteroid definitions following the exact bodies.js schema.
// DOES NOT OWN: meshes, gravity, or game state.
//
// CANON: These are new bodies in the SYL solar system. All existing IDs preserved.
// Faction hooks use existing faction IDs or null for unclaimed/contested.
// Placeholder factions are clearly marked.
//
// INTEGRATION: Import alongside BODIES in main.js:
//   import { BODIES } from './world/bodies.js';
//   import { BODIES_EXPANDED } from './world/bodies_expanded.js';
//   const ALL_BODIES = [...BODIES, ...BODIES_EXPANDED];
// ============================================================================

export const BODIES_EXPANDED = [
  {
    id: 'aethelgard',
    name: 'Aethelgard',
    position: [45000, 12000, -28000],
    radius: 5200,
    surfaceGravity: 11.2,
    realRadiusKm: 69911, realGravity: 24.79,
    colors: { low: 0x1a237e, mid: 0x3949ab, high: 0x5c6bc0, water: 0x0d1b2a },
    atmosphere: { color: 0x7986cb, height: 1400, density: 0.85 },
    terrain: { seed: 7777, amplitude: 70, octaves: 5, freq: 2.5 },
    seaLevel: 80,
    ownerFactionId: 'halcyon',
    landingZones: [
      {
        id: 'halcyon_enclave',
        name: 'Halcyon Enclave — Diplomatic Harbor',
        dir: [0.1, 1, 0.05],
        angularRadius: 0.05,
        flatten: true,
        factionId: 'halcyon',
        structures: 'outpost',
        discovery: { resourceItemId: 'salvage_alloy', note: 'Halcyon diplomatic outpost. Heavy alloy reserves for construction.' },
      },
      {
        id: 'aethelgard_ruins',
        name: 'Submerged Ruins — The Drowned City',
        dir: [0.6, -0.4, 0.7],
        angularRadius: 0.04,
        flatten: true,
        factionId: null,
        structures: 'relay',
        discovery: { resourceItemId: 'crystal_matrix', note: 'Pre-collapse city. Crystal deposits in the flooded foundations.' },
      },
    ],
    spawn: null,
    lore: 'Aethelgard — a water-world of deep oceans and storm-wracked archipelagos. The Halcyon Accord maintains its only surface enclave.',
  },
  {
    id: 'cryos',
    name: 'Cryos (Ice Moon)',
    position: [52000, 15000, -32000],
    radius: 1100,
    surfaceGravity: 1.45,
    realRadiusKm: 1560, realGravity: 1.35,
    colors: { low: 0x1a3c5a, mid: 0x4a7a9e, high: 0xa8c8dc },
    atmosphere: { color: 0xb0e0e6, height: 300, density: 0.3 },
    terrain: { seed: 1313, amplitude: 45, octaves: 6, freq: 5.0 },
    seaLevel: null,
    ownerFactionId: 'meridian',
    landingZones: [
      {
        id: 'meridian_ice_station',
        name: 'Meridian Ice Station Gamma',
        dir: [0.3, 0.9, 0.2],
        angularRadius: 0.05,
        flatten: true,
        factionId: 'meridian',
        structures: 'beacon',
        discovery: { resourceItemId: 'water_ice', note: 'Meridian ice-harvesting station. Pure water ice for fuel cracking.' },
      },
      {
        id: 'cryos_crack',
        name: 'The Great Crack — Fissure Field',
        dir: [-0.5, 0.5, 0.7],
        angularRadius: 0.06,
        flatten: true,
        factionId: null,
        structures: 'depot',
        discovery: { resourceItemId: 'ore_regolith', note: 'Exposed sub-surface ore veins in the planetary crack.' },
      },
    ],
    spawn: null,
    lore: 'Cryos orbits Aethelgard. A shell of ice over a dark ocean. Meridian Combine runs ice-to-fuel cracking operations here.',
  },
  {
    id: 'pyrrhus',
    name: 'Pyrrhus',
    position: [-22000, 8000, 42000],
    radius: 2800,
    surfaceGravity: 8.9,
    realRadiusKm: 4878, realGravity: 3.70,
    colors: { low: 0x3e1c0e, mid: 0x7a3c20, high: 0xbf5e36 },
    atmosphere: { color: 0xd84315, height: 600, density: 0.6 },
    terrain: { seed: 6666, amplitude: 110, octaves: 5, freq: 3.5 },
    seaLevel: null,
    ownerFactionId: 'fortis',
    landingZones: [
      {
        id: 'fortis_bastion',
        name: 'Fortis Bastion — Volcanic Perimeter',
        dir: [0.15, 0.95, 0.1],
        angularRadius: 0.045,
        flatten: true,
        factionId: 'fortis',
        structures: 'outpost',
        discovery: { resourceItemId: 'titanium_ore', note: 'Fortis military mining operation. Titanium-rich volcanic crust.' },
      },
      {
        id: 'pyrrhus_caldera',
        name: 'Caldera 7 — Abandoned Survey',
        dir: [0.8, -0.3, 0.5],
        angularRadius: 0.04,
        flatten: true,
        factionId: null,
        structures: 'beacon',
        discovery: { resourceItemId: 'exotic_matter', note: 'Unstable exotic matter detected in volcanic vents. Handle with care.' },
      },
    ],
    spawn: null,
    lore: 'Pyrrhus — a volcanic hellscape of lava plains and ash storms. Fortis maintains a hardened bastion on the northern shield.',
  },
  {
    id: 'veldora',
    name: 'Veldora (Ringed)',
    position: [8000, -25000, -55000],
    radius: 4800,
    surfaceGravity: 10.4,
    realRadiusKm: 58232, realGravity: 10.44,
    colors: { low: 0x2c3e2f, mid: 0x5d8c5a, high: 0x8fbc8f, water: 0x1e3a5f },
    atmosphere: { color: 0x81c784, height: 1200, density: 0.75 },
    terrain: { seed: 8888, amplitude: 85, octaves: 6, freq: 2.8 },
    seaLevel: 40,
    ownerFactionId: 'kindred',
    landingZones: [
      {
        id: 'kindred_mooring',
        name: 'Kindred Mooring — Fleet Anchorage',
        dir: [0.2, 0.9, 0.15],
        angularRadius: 0.055,
        flatten: true,
        factionId: 'kindred',
        structures: 'depot',
        discovery: { resourceItemId: 'fuel_hydrazine', note: 'Nomad fleet fuel reserve. Open to travelers at fair exchange.' },
      },
      {
        id: 'veldora_ring_mine',
        name: 'Ring Fragment Mine — The Shattered Arc',
        dir: [0.7, 0.3, 0.65],
        angularRadius: 0.05,
        flatten: true,
        factionId: 'registry',
        structures: 'beacon',
        discovery: { resourceItemId: 'titanium_ore', note: 'Ring-fragment mining operation. Dense metal alloys in the debris.' },
      },
    ],
    spawn: null,
    lore: 'Veldora — a ringed garden world with vast methane seas. The Kindred of the Long Walk anchor their fleet in the high atmosphere.',
  },
  {
    id: 'ironcore',
    name: 'Ironcore (Asteroid)',
    position: [-48000, -15000, -8000],
    radius: 280,
    surfaceGravity: 2.1,
    realRadiusKm: 262, realGravity: 0.38,
    colors: { low: 0x3a3a3a, mid: 0x5c5c5c, high: 0x7a7a7a },
    atmosphere: null,
    terrain: { seed: 4444, amplitude: 35, octaves: 4, freq: 6.0 },
    seaLevel: null,
    ownerFactionId: 'registry',
    landingZones: [
      {
        id: 'registry_foundry',
        name: 'Registry Foundry — Deep Core',
        dir: [0.5, 0.8, 0.3],
        angularRadius: 0.08,
        flatten: true,
        factionId: 'registry',
        structures: 'depot',
        discovery: { resourceItemId: 'titanium_ore', note: 'Registry deep-core foundry. Pure titanium ingots ready for shipment.' },
      },
      {
        id: 'ironcore_surface',
        name: 'Surface Claim 12 — Independent Strip',
        dir: [0.8, 0.4, 0.45],
        angularRadius: 0.06,
        flatten: true,
        factionId: null,
        structures: 'beacon',
        discovery: { resourceItemId: 'salvage_alloy', note: 'Independent strip-mining claim. Alloy stockpiles under tarps.' },
      },
    ],
    spawn: null,
    lore: 'Ironcore — a nickel-iron asteroid with surface gravity far above its size. The Registry runs a deep-core foundry here.',
  },
  {
    id: 'dunewind',
    name: 'Dunewind',
    position: [32000, -8000, 18000],
    radius: 2400,
    surfaceGravity: 3.71,
    realRadiusKm: 3389, realGravity: 3.71,
    colors: { low: 0x5c3a1e, mid: 0x8b5a2b, high: 0xc19a6b },
    atmosphere: { color: 0xd7a86e, height: 400, density: 0.25 },
    terrain: { seed: 9999, amplitude: 65, octaves: 5, freq: 3.0 },
    seaLevel: null,
    ownerFactionId: 'freeport',
    landingZones: [
      {
        id: 'freeport_dune',
        name: "Freeport Dune Station — Smuggler's Rest",
        dir: [0.1, 0.95, 0.2],
        angularRadius: 0.05,
        flatten: true,
        factionId: 'freeport',
        structures: 'depot',
        discovery: { resourceItemId: 'fuel_hydrazine', note: 'Freeport smuggling waystation. Fuel and contraband available.' },
      },
      {
        id: 'dunewind_wreck',
        name: 'Wreck of the Typhon — Crash Site',
        dir: [0.6, 0.4, 0.7],
        angularRadius: 0.045,
        flatten: true,
        factionId: null,
        structures: 'relay',
        discovery: { resourceItemId: 'wiring_loom', note: 'Crashed survey vessel. Salvageable electronics and wiring.' },
      },
    ],
    spawn: null,
    lore: 'Dunewind — a Mars-like desert of rust-red dunes and dust storms. Freeport Syndicate runs a waystation in the deep equatorial basin.',
  },
];
