// GENERATED by tools/gen-registry.mjs - do not hand-edit. Every src/worlds/<name>/def.js.
// One line per folder; merged with git's union driver (.gitattributes). Run: node tools/gen-registry.mjs

import w_callisto from './callisto/def.js';
import w_ceres from './ceres/def.js';
import w_deimos from './deimos/def.js';
import w_earth from './earth/def.js';
import w_fortis from './fortis/def.js';
import w_greenhaven from './greenhaven/def.js';
import w_jupiter from './jupiter/def.js';
import w_mars from './mars/def.js';
import w_mercury from './mercury/def.js';
import w_moon from './moon/def.js';
import w_neptune from './neptune/def.js';
import w_phobos from './phobos/def.js';
import w_saturn from './saturn/def.js';
import w_sun from './sun/def.js';
import w_uranus from './uranus/def.js';
import w_venus from './venus/def.js';

export const WORLD_DEFS = [
  w_callisto,
  w_ceres,
  w_deimos,
  w_earth,
  w_fortis,
  w_greenhaven,
  w_jupiter,
  w_mars,
  w_mercury,
  w_moon,
  w_neptune,
  w_phobos,
  w_saturn,
  w_sun,
  w_uranus,
  w_venus,
];
