// Homeguard (Earth): the ones who stay, rebuild and fortify. Sea walls, farms, flashy fortified cities. BIBLE-v3 4.5.
// Look: harbour navy and limestone, brick red, beacon gold. Built to last a storm surge and to be seen from a long way off.
export default {
  id: 'homeguard', name: 'Homeguard', kind: 'faction', home: 'earth',
  tagline: 'We stay. We rebuild. We put a light on top.',
  ethos: 'Heavy, warm, proud. Everything is built to outlast the weather and to say so: thick walls, big gold lights, flags, civic pride. A rich people who know exactly what they would lose.',
  palette: { primary: 0x2f4a63, secondary: 0xc9b79a, accent: 0xe0a53a, trim: 0x8a3a2c, dark: 0x1b2430, light: 0xf0ebe0, extra: [0x5d8a86, 0x6f7f8c] },
  lights: { ambient: 0xffe9c4, work: 0xfff1d6, signal: 0xffc24a, alarm: 0xff5a3c },
  materials: [
    { id: 'seawall-concrete', name: 'Sea-wall concrete', color: 0x9a9c98, roughness: 0.92, metalness: 0.0, use: 'walls, quays, barriers: cast in big panels with ribbing and tide stains at the foot' },
    { id: 'limestone-facing', name: 'Limestone facing', color: 0xc9b79a, roughness: 0.8, metalness: 0.0, use: 'the fronts of civic halls and gate towers' },
    { id: 'harbour-navy', name: 'Harbour-navy steel', color: 0x2f4a63, roughness: 0.5, metalness: 0.45, use: 'doors, shutters, railings, ship hulls' },
    { id: 'brick-red', name: 'Fired brick', color: 0x8a3a2c, roughness: 0.88, metalness: 0.0, use: 'housing blocks, chimneys, the older districts' },
    { id: 'beacon-brass', name: 'Beacon brass', color: 0xd9a441, roughness: 0.3, metalness: 0.9, use: 'lamp housings, plaques, door furniture, the lights on top of everything' },
  ],
  signs: {
    font: 'Serif civic capitals', fontStack: 'Georgia, "Times New Roman", serif', weight: 700, upper: true, tracking: 0.08,
    plate: { bg: 0x1b2430, fg: 0xf0ebe0, edge: 0xd9a441, radius: 0.04, rivets: true },
    warning: { bg: 0xe0a53a, fg: 0x1b2430, stripe: [0xe0a53a, 0x1b2430] },
    banner: { bg: 0x2f4a63, fg: 0xf0ebe0 },
    emblem: { shape: 'seawall', fg: 0xe0a53a, bg: 0x2f4a63, meaning: 'a crenelled wall tower standing above three wave lines: the wall holds' },
    numbering: { pattern: 'WARD ## / GATE #', example: 'WARD 12 / GATE 3' },
    places: ['Surge Gate', 'Lantern Quay', 'The Long Wall', 'Harvest Row', 'Beacon Hall', 'Tidewatch Steps'],
    slogans: ['WE STAY.', 'THE WALL HOLDS.', 'NOT LEAVING. NOT EVEN FOR THE VIEW.', 'MIND THE SURGE, MIND THE STEP.', 'EVERY LIGHT ON. EVERY NIGHT.'],
    graffiti: ['SKYWARD CANNOT HEAR YOU FROM UP THERE', 'IF IT FLOODS WE WILL CHARGE FOR THE BOATS', 'THIS WALL IS 11 METRES OF OPINIONS'],
  },
  uniforms: {
    worker: { cloth: 0x6e7c90, trim: 0xe0a53a, note: 'navy canvas coat, gold armband, hard cap with a brass lamp: the wallwarden crews' },
    civilian: { cloth: 0xa8967a, trim: 0x8a3a2c, note: 'good wool in sandstone and brick: nobody on Earth dresses down in front of a neighbour' },
    guard: { cloth: 0x4a5a70, trim: 0xe0a53a, note: 'dark harbour coat with gold epaulettes and a long flashlight, helmet with a brass lamp', helmet: { shell: 0x2f4a63, trim: 0xd9a441, visorTint: 0x7a5a32, visorOpacity: 0.6 } },
    officer: { cloth: 0x3a4d63, trim: 0xe0a53a, note: 'navy dress coat, gold braid on the cuff; the warden wears the key of the gate on a chain' },
    pilot: { cloth: 0x8a7a64, trim: 0xe0a53a, note: 'leather flight jacket over wool; ferry pilots, a bit too proud of it' },
    trader: { cloth: 0x9a7b62, trim: 0x2f4a63, note: 'a long apron, a ledger, rolled sleeves' },
    leader: { cloth: 0x2f4a63, trim: 0xe0a53a, note: 'the best navy coat on the wall with the beacon brooch; always standing slightly higher than whoever they are talking to' },
  },
  hair: [0x1c140f, 0x3b2416, 0x6b3a22, 0x7a736c, 0xb6b0a4],
  architecture: {
    massing: 'Thick, stepped, battered walls with a lean inward; towers at every gate; whole districts behind a wall with a promenade on top. Cities that look like they are expecting company.',
    roofs: 'steep pantile roofs on housing; flat promenade roofs on the wall; a lantern cupola on every hall',
    windows: 'tall, narrow, shuttered; arched on civic buildings; the shutters are navy and close in storm weather',
    lighting: 'warm gold from every gate, wall top and window; a beacon on each tower that sweeps; flashy at night on purpose',
    ground: 'grey sea-wall concrete, brick paving, planter boxes of vegetables in every spare corner',
    motifs: ['crenelled wall tower', 'three wave lines', 'beacon lamp', 'stepped battered wall', 'shutters', 'planter farm box'],
    props: ['sandbag stack painted navy', 'tide gauge post', 'boat on a trailer', 'brass bell', 'vegetable cart', 'storm shutters stacked', 'flag halyard'],
    avoid: ['white launch-pad clean lines (that is Skyward)', 'flat blue glass towers (that is Technos)', 'bare concrete with no colour'],
  },
  livery: {
    hull: 0x2f4a63, hullAlt: 0x3f5f7e, belly: 0x1b2430, trim: 0xc9b79a, accent: 0xe0a53a, engineGlow: 0xffc24a,
    stripe: { kind: 'band', colors: [0xe0a53a, 0xf0ebe0], widthFrac: 0.06, note: 'a gold band below the cockpit with a thin white line under it' },
    shape: 'Blunt, deep, rounded like a harbour tug: thick plating, big windows, a lamp on the roof. Few ships, each one cared for. Reads as a lifeboat built by people who like gold.',
    registryPrefix: 'HG-', nameStyle: 'a place or a virtue, brass lettering on the bow: LANTERN QUAY, STEADFAST',
    weathering: { grime: 0.25, scorch: 0.1, patchwork: 0 }, navBeacon: 0xffc24a,
  },
};
